### ISSUE TITLE
Add tests (run via CI)

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2024-b-grass-qgis-colors-convert#12]
Add tests:

- [x] use sample data (corine), apply color table, check result (`filecmp` - diff generated file and reference (`tests\reference\corine.qml`)
- [x] implement tests using `pytest` package - https://docs.pytest.org/en/8.2.x/
- [x] run tests via GitHub workflows on very commit
- [x] clean-up `test` directory in git

**Comment by pesekon2** [comment]
An example of a consitestency test written in pytest: <https://github.com/ctu-geoforall-lab-projects/phd-pesek-2022/blob/master/src/test/consistency_test.py#L1-L68> (the following lines are unnecessary, it just checks multiple different settings; the same applies to the for loops; instead of `train`, you would call your own code)

How to call this pytest in GH workflows: <https://github.com/ctu-geoforall-lab-projects/phd-pesek-2022/blob/master/.github/workflows/consistency_test.yml>

**Comment by jehlijos** [comment]
I have merged the pr into master, because as was able to run GitHub workflow only from master. Test works via Github Actions now in master.
